[package]
name = "charcot_dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.31"  # For timestamps
rustyline = "12.0.0"  # For readline functionality and autocompletion
